CREATE DATABASE IF NOT EXISTS yii2_database CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'yii2_user'@'%' IDENTIFIED BY 'yii2_password';
GRANT ALL PRIVILEGES ON yii2_database.* TO 'yii2_user'@'%';
FLUSH PRIVILEGES;